### ISSUE TITLE
There are deprecations in torch 1.1.0

### ISSUE THREAD

**Issue by 18022443868** [TAMU-VITA/FasterSeg#31]
Traceback (most recent call last):
  File "E:/vSLAM/FasterSeg-master/train/train.py", line 28, in <module>
    from eval import SegEvaluator
  File "E:\vSLAM\FasterSeg-master\train\eval.py", line 9, in <module>
    from engine.evaluator import Evaluator
  File "E:\vSLAM\FasterSeg-master\tools\engine\evaluator.py", line 11, in <module>
    from utils.pyt_utils import load_model, link_file, ensure_dir
  File "E:\vSLAM\FasterSeg-master\tools\utils\pyt_utils.py", line 23, in <module>
    def reduce_tensor(tensor, dst=0, op=dist.ReduceOp.SUM, world_size=1):
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'

pytorh=1.1.0   windows10

**Comment by egedib** [comment]
If you want to evaluate/test only, you can comment those lines (23-37) out.

It doesn't solve your problem if you want to train though.

**Comment by 18022443868** [comment]
How to train on WIN10 single GPU?

**Comment by chenwydj** [comment]
Hi @18022443868!

Thank you for your interest in our work!

As mentioned in our [Readme](https://github.com/TAMU-VITA/FasterSeg/blob/master/README.md), we only test our code in Ubuntu environment. We did not test on Windows.
